export default {
  GET_CURRENT_USER: 'GET_CURRENT_USER',
  GET_USER_PROFILE: 'GET_USER_PROFILE',
  GET_ACTIVE_REPO: 'GET_ACTIVE_REPO',
  CLEAR_ACTIVE_REPO: 'CLEAR_ACTIVE_REPO',
  AWS_URL: 'https://s3-us-west-1.amazonaws.com/gitcoders/'
}
